# Generated by Django 3.1.5 on 2021-02-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('regproductid', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('weightunit', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=12)),
                ('subcategory', models.CharField(max_length=12)),
                ('vendor', models.CharField(max_length=30)),
            ],
        ),
    ]
