# Generated by Django 3.1.5 on 2021-02-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
