# Generated by Django 3.1.5 on 2021-02-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20210202_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
