# Generated by Django 3.1.5 on 2021-02-05 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=30)),
                ('companyregid', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('bankaccountholder', models.CharField(max_length=30)),
                ('bankacccountnumber', models.CharField(max_length=30)),
                ('bankacccountifsc', models.CharField(max_length=30)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.usertype')),
            ],
        ),
    ]
