# Generated by Django 3.1.5 on 2021-02-10 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resellers',
            old_name='login_id',
            new_name='login',
        ),
        migrations.AddField(
            model_name='resellers',
            name='requestdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='resellers',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('regproductid', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('weightunit', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=12)),
                ('subcategory', models.CharField(max_length=12)),
                ('vendor', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller.resellers')),
            ],
        ),
    ]
