# Generated by Django 3.1.5 on 2021-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0002_auto_20210210_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='regproductid',
            new_name='reg_productid',
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
