# Generated by Django 3.1.5 on 2021-02-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0003_auto_20210212_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
