# Generated by Django 3.1.5 on 2021-02-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0004_auto_20210215_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.FileField(upload_to='product_images/'),
        ),
    ]
