# Generated by Django 3.1.5 on 2021-03-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0007_auto_20210215_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='vendor',
            field=models.CharField(max_length=100),
        ),
    ]
